// resources/assets/scripts/components/MessageBox.vue
<template>
    <div class="lg:inline-flex" role="alert">
        <span class="title" v-html="title" v-if="title && title.length > 0"></span>
        <span class="message" v-html="message"></span>
    </div>
</template>

<script lang="ts">
    export default {
        name: 'message-box',
        props: {
            title: {type: String, required: false},
            message: {type: String, required: true}
        },
    };
</script>

// resources/scripts/components/MessageBox.tsx
import * as React from 'react';

export type FlashMessageType = 'success' | 'info' | 'warning' | 'error';

interface Props {
    title?: string;
    children: string;
    type?: FlashMessageType;
}

export default ({ title, children, type }: Props) => (
    <div className={`lg:inline-flex alert ${type}`} role={'alert'}>
        {title && <span className={'title'}>{title}</span>}
        <span className={'message'}>
            {children}
        </span>
    </div>
);
